pipeline {
    agent any
    stages {
        stage ("Check www.example.com response code") {
            steps{
                sh  '''
                    TOKEN=""
                    GROUP_ID=""
                    command=$(curl -o /dev/null -s -w %{http_code} www.example.com)
                    
                    
                    if [ "${command}" != "200" ]; then
                      message="www.example.com response code != 201."
                      curl -X GET "https://api.telegram.org/bot${TOKEN}/sendMessage" \
                          -d "chat_id=${GROUP_ID}&text=${message}"
                    fi                
                '''
            }
        }
    }
}
