pipeline {
    agent any
    stages {
        stage ("Request website") {
            steps{
                script{
                    response_code = sh (
                        script: "curl -o /dev/null -s -w %{http_code} www.example.com",
                        returnStdout: true
                    ).toInteger()
                    
                    echo "${response_code}"                    
                }

            }
        }
        stage ("Check response code") {
            steps{
                script{
                    if ( response_code != 200 ){
                        sh "false"
                    }             
                }

            }
        }
    }
    post {
        success{
            echo "success"
        }
        failure{
            script {
                withCredentials([string(credentialsId: 'ithome-telegram-bot-token', variable: 'TOKEN')]){
                    withCredentials([string(credentialsId: 'ithome-telegram-notification-group', variable: 'GROUP_ID')]){                
                    sh '''
                        message="www.example.com response code != 200."
                        curl -X GET https://api.telegram.org/bot${TOKEN}/sendMessage -d "chat_id=${GROUP_ID}&text=${message}"
                    '''
                    }
                }
            }
        }
        
    }
}
